### ISSUE TITLE
Cannot assign `function` to parameter `Callback`

### ISSUE THREAD

**Issue by mrjones2014** [folke/neodev.nvim#85]
Am I doing something wrong here?

![image](https://user-images.githubusercontent.com/8648891/198997558-a34fc61f-4f8b-404d-87e5-b14f44d38115.png)

**Comment by folke** [comment]
This has been fixed upstream, so works as expected on Neovim nightly.

**Comment by bigzhu** [comment]
NVIM v0.9.0-dev-1566+g6e8ed5aba-dirty still has this error.

**Comment by folke** [comment]
@bigzhu then your lua runtime must be messed up, since it really has been fixed upstream.
I know, because I'm the one that did the changes.

Those annotations are not even coming from Neodev.

![image](https://user-images.githubusercontent.com/292349/202903662-da794eeb-a91e-4a5d-9371-151c4603a125.png)

**Comment by wookayin** [comment]
Fixed in neovim [548a4e25](https://github.com/neovim/neovim/commit/548a4e258777a405cc2b1225cab9a8292924407b) (v0.9.0+)
